/**
 *
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */
package org.opendaylight.controller.sal.core;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
  name = "node",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "node",
  namespace = ""
)
public class Node implements java.io.Serializable {

  private java.lang.String _id;
  private java.lang.String _type;



  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "id",
    namespace = ""
  )
  public java.lang.String getId() {
    return this._id;
  }

  /**
   * (no documentation provided)
   */
  public void setId(java.lang.String _nodeIDString) {
    this._id = _nodeIDString;
  }




  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "type",
    namespace = ""
  )
  public java.lang.String getType() {
    return this._type;
  }

  /**
   * (no documentation provided)
   */
  public void setType(java.lang.String _type) {
    this._type = _type;
  }

}
