FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# FIWARE OFNIC

TODO

# Allowed HTTPs requests:  
PUT   : To create resource   
POST  : Update resource  
GET   : Get a resource or list of resources  
DELETE : To delete resource  
  
